version: "3"
services:

  web:
    image: sarrufat/ang-games-cli:latest
    restart: always
    ports:
      - "8080:80"
    networks:
      - backend

  play:
    image: sarrufat/chess-go-kit:latest
    restart: always
    ports:
      - "9000"
    expose:
      - "9000"
    networks:
      - backend

  prometheus:
    image: sarrufat/chess-go-prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    user: "104"
    networks:
      - backend

networks:
  backend:
