version: "3"
services:

  web:
    image: sarrufat/ang-games-cli:latest
    restart: always
    ports:
      - "8080:80"
    networks:
      - backend

  play:
    image: sarrufat/chess-go-kit:latest
    restart: always
    ports:
      - "9000"
    expose:
      - "9000"
    networks:
      - backend

  prometheus:
    image: sarrufat/chess-go-prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    networks:
      - backend

networks:
  backend:
