{
 "title": "GO data",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes" }
   ]
  },
  {
   "title": "Total CPU",
   "type": "graph",
   "description": "Total CPU Time in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Go CC duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds" }
   ]
  }
 ]
}