apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: play
  name: play
spec:
  replicas: 2
  selector:
    matchLabels:
      app: play
  template:
    metadata:      
      labels:
        app: play
    spec:
      containers:
      - image: sarrufat/chess-go-kit:latest
        imagePullPolicy: ""
        name: play
        ports:
        - containerPort: 9000
