apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: sarrufat/chess-go-prometheus:latest
        imagePullPolicy: ""
        name: prometheus
        ports:
        - containerPort: 9090